sudo: required

language: bash

services:
  - docker

script:
  - set -e
  - TEST_MODE=yes make generate-devdoc
  - export QUICKSTART_MIN_ZOOM=0
  - export QUICKSTART_MAX_ZOOM=14
  - ./quickstart.sh enfield
